treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :books
end

treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/app/models/book.rb
class Book < ApplicationRecord
    validates :title, :author, :publication_year, :genre, :abstract, presence: true
end

treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      flash.now[:error] = "Todos campos devem ser preenchidos"
      render :new
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :author, :publication_year, :genre, :abstract)
    end
end

treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.all
  end
end

treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/app/helpers/application_helper.rb
module ApplicationHelper
end

treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/app/views/books/new.html.erb
<%= form_with model: @book do |f| %>
    <div>
         <%= f.label 'Título:' %><br> 
        <%= f.text_field :title, id:"Título" %>
    </div>

    <div>
        <%= f.label 'Autor(a):' %><br>
        <%= f.text_field :author, id:"Autora" %>
    </div>

    <div>
        <%= f.label 'Ano de publicação:' %><br>
        <%= f.number_field :publication_year, id:"Ano de publicação" %>
    </div>

    <div>
        <%= f.label 'Gênero:' %><br>
        <%= f.text_field :genre, id:"Gênero"  %>
    </div>

    <div>
        <%= f.label 'Resumo:' %><br>
        <%= f.text_field :abstract, id:"Resumo" %>
    </div>

    <div>
        <%= f.submit "Enviar" %>
    </div>

    <% if flash[:error] %>
        <p>Todos campos devem ser preenchidos</p>
    <% end %>
<% end %>

treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p><%= @book.author %></p>
<p><%= @book.publication_year %></p>
<p><%= @book.abstract %></p>
<p><%= @book.genre %></p>
<%= link_to 'Voltar', root_path %>

treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/app/views/home/index.html.erb
<h1>Catálogo de Livros</h1>
<p>Boas vindas!</p>

<% @books.each do |book| %>
  <h3><%= link_to book.title, book_path(book) %></h3>
  <p><%= book.author %> </p>
  <p><%= book.publication_year %> </p>
<% end %>

<p> <%= link_to 'Registrar livro', new_book_path(@books) %> </p>

treinadev/orientacao-objetos/catalogo-livros/book-catalogue-create/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCatalogueParte3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>